use_frameworks!

target 'NXDrawKit_Example' do
  pod 'NXDrawKit', :path => '../'
  pod 'SnapKit', '~> 3.0.0'
  pod 'RSKImageCropper'

  target 'NXDrawKit_Tests' do
    inherit! :search_paths

    
  end
end
